#!/bin/bash
# Initially based on a snippet from the greenlet project.
# This needs to be run from the root of the project.
set -e
export PYTHONUNBUFFERED=1
export PYTHONDONTWRITEBYTECODE=1

if [ -d /RelStorage -a -d /opt/python ]; then
    # Running inside docker
    yum -y install libffi-devel
    cd /RelStorage
    rm -rf wheelhouse
    for variant in `ls -d /opt/python/cp{27,34,35,36}*`; do
        rm -rf dist build *.egg-info
        $variant/bin/pip install -U cffi setuptools wheel
		$variant/bin/pip install -U .
        PATH=$variant/bin:$PATH $variant/bin/python setup.py bdist_wheel
        auditwheel repair dist/*.whl
    done
    rm -rf dist build *.egg-info
    exit 0
fi

docker run --rm -ti -v "$(pwd):/RelStorage" quay.io/pypa/manylinux1_x86_64 /RelStorage/scripts/releases/$(basename $0)
