#!/bin/bash
# Initially based on a snippet from the greenlet project.
# This needs to be run from the root of the project.
# To update: docker pull quay.io/pypa/manylinux2010_x86_64
set -e
export PYTHONUNBUFFERED=1
export PYTHONDONTWRITEBYTECODE=1

if [ -d /RelStorage -a -d /opt/python ]; then
    # Running inside docker
    yum -y install libffi-devel
    cd /RelStorage
    rm -rf wheelhouse
    mkdir wheelhouse
    for variant in `ls -d /opt/python/cp{27,35,36,37}*`; do
        echo "Building $variant"
        mkdir /tmp/build
        cd /tmp/build
        git clone /RelStorage RelStorage
        cd RelStorage
        $variant/bin/pip install -U pip
        $variant/bin/pip install -U cffi setuptools
        PATH=$variant/bin:$PATH $variant/bin/pip wheel . -w dist
        auditwheel repair dist/RelStorage*.whl
        cp wheelhouse/RelStorage*.whl /RelStorage/wheelhouse
        cd /RelStorage
        rm -rf /tmp/build
    done
    rm -rf dist build *.egg-info
    exit 0
fi

docker run --rm -ti -v "$(pwd):/RelStorage" quay.io/pypa/manylinux2010_x86_64 /RelStorage/scripts/releases/$(basename $0)
