#!/bin/bash
# Initially based on a snippet from the greenlet project.
# This needs to be run from the root of the project.
set -e
export PYTHONUNBUFFERED=1
export PYTHONDONTWRITEBYTECODE=1

if [ -d /relstorage -a -d /opt/python ]; then
    # Running inside docker
    yum -y install libffi-devel
    cd /relstorage
    rm -rf wheelhouse
    for variant in `ls -d /opt/python/cp{27,3}*`; do
        rm -rf dist build *.egg-info
        $variant/bin/pip install -U cffi setuptools wheel
        PATH=$variant/bin:$PATH $variant/bin/python setup.py bdist_wheel
        auditwheel repair dist/*.whl
    done
    rm -rf dist build *.egg-info
    exit 0
fi

docker run --rm -ti -v "$(pwd):/relstorage" quay.io/pypa/manylinux1_x86_64 /relstorage/.travis/$(basename $0)
